import { describe, it } from 'node:test';
import assert from 'node:assert';
import { createChess, getLegalMoves } from '../chessEngine';
import { computeAiMove } from '../chessAi';
import type { AiLevel } from '../chessAi';

describe('ChessAi - 6 AI Difficulty Levels', () => {
  const levels: AiLevel[] = ['BEGINNER', 'EASY', 'NORMAL', 'HARD', 'EXPERT', 'MASTER'];

  for (const level of levels) {
    it(`level ${level} generates a legal move from starting position`, async () => {
      const chess = createChess();
      const legalMoves = getLegalMoves(chess);

      const result = await computeAiMove(chess, level);
      assert.ok(result.move, `AI (${level}) must return a move`);

      // Verify the move is among the legal moves
      const isLegal = legalMoves.some(
        (m) => m.from === result.move.from && m.to === result.move.to
      );
      assert.ok(isLegal, `Move ${result.move.san} generated by AI (${level}) must be legal`);
      assert.ok(result.nodes > 0, `Search nodes must be tracked (> 0)`);
      assert.ok(result.depth >= 1, `Depth must be >= 1`);
    });
  }

  it('NORMAL and higher AI finds immediate Mate-in-1', async () => {
    // Scholar's Mate in 1 position: White queen on h5, bishop on c4. Black king on e8.
    // White can play Qxf7#
    const chess = createChess('r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4');

    const result = await computeAiMove(chess, 'NORMAL');
    assert.strictEqual(result.move.from, 'h5');
    assert.strictEqual(result.move.to, 'f7');
    assert.ok(result.move.san.includes('#') || result.move.isCheckmate);
  });

  it('HARD AI captures unprotected valuable pieces', async () => {
    // White queen on d4 is hanging and unprotected. Black knight on c6 can take it (Nxd4) or pawn exd4
    const chess = createChess('r1bqkbnr/pppp1ppp/2n5/4p3/3Q4/8/PPP1PPPP/RNB1KBNR b KQkq - 0 4');

    const result = await computeAiMove(chess, 'HARD');
    assert.strictEqual(result.move.to, 'd4', 'AI should capture the hanging queen on d4');
  });

  it('EXPERT AI performs iterative deepening with metrics', async () => {
    const chess = createChess();
    const result = await computeAiMove(chess, 'EXPERT');

    assert.ok(result.depth >= 3, `Expert AI depth should reach at least 3 (was ${result.depth})`);
    assert.ok(result.nodes >= 20, `Expert AI should evaluate nodes (evaluated ${result.nodes})`);
    assert.ok(result.timeMs >= 0, `Expert AI elapsed time should be recorded`);
  });

  it('MASTER AI utilizes move ordering and quiescence search', async () => {
    const chess = createChess();
    const result = await computeAiMove(chess, 'MASTER');

    assert.ok(result.depth >= 3, `Master AI depth should reach at least 3 (was ${result.depth})`);
    assert.ok(result.nodes >= 30, `Master AI nodes evaluated: ${result.nodes}`);
    assert.ok(typeof result.score === 'number', `Score should be a number`);
  });
});
